### PR TITLE
Update search when tags are added

### PR DESCRIPTION
**Pull request by alran**
### Summary of Changes

This PR adds a search proxy class. When a user adds a tag to a table, we update the search document for the table to reflect the most current version of the table.

### Tests

I added tests for the TableTagAPI and `update_elastic` method

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes. 
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes `make test`
- [x] I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by feng-tao** [comment]
will take a look next week, but from first glance is there any reason not put it in search repo instead of here? And is it possible to use document API in search repo for this purpose?

**Comment by jornh** [comment]
@feng-tao I think it _is_ using the document API of search service - here: https://github.com/lyft/amundsenmetadatalibrary/pull/76/files#diff-33eee38c1581d71337b2eafb0741c1e5R198-R199

I can think of two reasons this should live here:
* The Metadata service gets the API calls for updating the tags. This can be either from frontend or elsewhere. So the metadata service gets the triggering event.
* It queries Neo4j - here (so the metadata service hides knowledge of Neo4j from search): 

https://github.com/lyft/amundsenmetadatalibrary/blob/05580235136f0f5c00b7ce4c5117724a94128f0c/metadata_service/proxy/neo4j_proxy.py#L554

**Comment by alran** [comment]
@feng-tao pinging you for a review on this when you have time!

**Comment by benjaminjack** [comment]
Any updates on this?

**Comment by ak93-ak93** [comment]
Any updates on this?

**Comment by alran** [comment]
this PR is kind of old now.. I can refresh it this week so that it doesn't have conflicts

**Comment by alran** [comment]
Updated and resolved merge issues! I also added a config value so that if people don't want to update their elastic in this way, they don't have to CC @jinhyukchang

**Comment by JavierLTPromofarma** [comment]
This is a great feature. I am looking forward to have it merged! Thank you for your work guys

**Comment by Dewwi** [comment]
This  is indeed a great feature. Can't wait to have this merged!

**Comment by shanshan-gusto** [comment]
Any estimated timeline when this is going to get merged? We're launching Amundsen within our Org in 2 weeks, and would like to include this feature!!

**Comment by feng-tao** [comment]
It has been discussed in https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1587728303150600 which I think we should put the code in frontend which will update the index. 

In the mean time, @shanshan-gusto great to hear that your team is launching Amundsen, could you update the readme(https://github.com/lyft/amundsen#who-uses-amundsen) to put your team there when you have a chance? Thanks.

**Comment by shanshan-gusto** [comment]
@feng-tao Will do when we deploy in prod! Thanks again for such an amazing product!

**Comment by ibnipun10** [comment]
Any updates on the issue please.

**Comment by alran** [comment]
I am considering closing this PR since it sounds like this isn't the direction you want to go @feng-tao. If you change your mind, I am happy to update this PR to work properly with more recent changes to Amundsen (we just pulled down a refresh of changes to our version)

**Comment by feng-tao** [comment]
thanks @alran , I felt that we should put the code in frontend to avoid intervene metadata and search service. But let's keep the pr here as a reference implementation once we / someone from the community has the chance to implement it.

**Comment by alran** [comment]
sounds good!

**Comment by verdan** [comment]
I completely agree with what @feng-tao mentioned. Our frontend service orchestrates as an event service in this case, and that should be the place to update the indexes asynchronously as it already has the connection to the search service.

**Comment by dorianj** [comment]
Closing in favor of https://github.com/amundsen-io/amundsenfrontendlibrary/pull/883

**Pull request closed without merging**
