### PR TITLE
chore: updated version of library for new release

### PR DESCRIPTION
**Pull request by allisonsuarez**
### Summary of Changes

Major release given that we no longer support old badges.

### Tests

N/A
### Documentation

N/A

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes `make test`

### CODE REVIEW

**Review by Golodhros — APPROVED** [review]
LGTM

**Review by feng-tao — APPROVED** [review]
would be good to include a brief note like databuilder on the change/pr list

**Review by dikshathakur3119 — APPROVED** [review]

**Comment by allisonsuarez** [comment]
> would be good to include a brief note like databuilder on the change/pr list

What do you mean?

**Comment by feng-tao** [comment]
when you create the new release, put up a similar note like databuilder that lists out all the change / commit with pr.

**Pull request merged**
